### ISSUE TITLE
Introduksjonkurs til Github og smidig metodikk - 25. september 2024

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/styringssystem#18]
Oppgaver:
- [x] Avklare dato for kurset
- [ ] Forberedelsesmøte før kurset
- [ ] Sende ut innkalling til kurs
- [ ] Sende ut informasjon om opprettelse av brukere i Github
- [ ] Gjennomføre kurset
- [ ] Sende ut evaluering etter kurset til deltakerne
- [ ] Sende ut kursmateriell til deltakerne
- [ ] Gjennomgang av evalueringen
- [ ] Slette innsendte svar fra evalueringen

**Comment by hildemari** [comment]
Kurs flyttes frem til 17/10 på grunn av få deltakere. Lukker denne.
