### ISSUE TITLE
Baksia - avklaringer knyttet til Samarbeidsportalen

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/styringssystem#36]
Vi må se på sammenhengen mellom Baksia og Samarbeidsportalen. 

- [ ] Hvilke informasjon ligger hvor
- [ ] Hvilke informasjon skal ligge hvor
- [ ] +++

**Comment by arild-65** [comment]
Denne saken kan lukkes. Det blir ikke flyttet noe fra Samarbeidisportalen  til Baksia.
