### ISSUE TITLE
Anskaffelse Dokumentasjonsstyring

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/styringssystem#9]
- [ ] Konsulentbistand (kartlegge behov og kravspekke stilling)
- [ ] Melde inn behov for stilling til lederlaget
- [ ] Grensedragning mot FEL

**Comment by TinaJMoe** [comment]
Saksunderlag Konsulentbistand Dokumentstyring 
https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/[saksframlegg_dokstyring_jun24.docx](https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/saksframlegg_dokstyring_jun24.docx?d=w9862be66c3794537ac799baa7fbda357&csf=1&web=1&e=IM5olw)?d=w9862be66c3794537ac799baa7fbda357&csf=1&web=1&e=IM5olw

**Comment by SnorreTE** [comment]
Dette er punktene vi må levere mer på når saken kommer opp igjen etter ferien (ut fra mine ufullstendige notater 😊):

-	Klar bestilling/leveranse til ekstern konsulent/firma
	Punktliste i prioritert rekkefølge

-	Ønsket effekt etter gjennomgang fra konsulent/firma

-	Sjekk med økonomi team (budsjett for innleie)

**Comment by TinaJMoe** [comment]
Planlagt andre behandling i Ledermøtet 1. okt
Saksunderlag her [https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/Dokumentasjonsstyring/[Saksframlegg_Dokumentstyring_sept_24.docx](https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/Dokumentasjonsstyring/Saksframlegg_Dokumentstyring_sept_24.docx?d=w33efd81e843f49ef9c97b714b13feb35&csf=1&web=1&e=G1zWt0)?d=w33efd81e843f49ef9c97b714b13feb35&csf=1&web=1&e=G1zWt0](url)

**Comment by arild-65** [comment]
Hadde (4. okt) forberedende møte med Sol/Innkjøp vedr. anskaffelse av konsulent. Kladd behovsmelding:
https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/Dokumentasjonsstyring/[behovsmelding_innleie_okt24.docx](https://digdir.sharepoint.com/:w:/r/sites/TeamStyringssystem/Delte%20dokumenter/General/Dokumentasjonsstyring/behovsmelding_innleie_okt24.docx?d=wd749ce0e83ab48e09eaabe67b80752a8&csf=1&web=1&e=w7XekX)?d=wd749ce0e83ab48e09eaabe67b80752a8&csf=1&web=1&e=w7XekX
